version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  rabbit:
    image: rabbitmq:3-management #has the management plugin preinstalled
    ports:
      - "5672:5672" #main port
      - "15672:15672" #admin port

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
